import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import type { GraphData } from './types'
import './index.css'

// Data enters the app exactly once, synchronously, from the JSON island
// kepra-index.py injects into index.html at generation time — no fetch, no
// loading state. Two failure modes are handled explicitly rather than
// left to crash: the placeholder never having been replaced (viewer opened
// unbuilt/uninjected) and malformed JSON (a partially-written graph.json).
function readGraphData(): { graph: GraphData | null; parseError: string | null } {
  const el = document.getElementById('kepra-graph-data')
  const raw = el?.textContent?.trim()
  if (!raw) {
    return {
      graph: null,
      parseError:
        'No graph data is embedded in this page. Open graphify-out/graph.html from your vault (generated by kepra-index) rather than this file directly.',
    }
  }
  try {
    const parsed = JSON.parse(raw)
    const nodes = Array.isArray(parsed.nodes) ? parsed.nodes : []
    const links = Array.isArray(parsed.links)
      ? parsed.links
      : Array.isArray(parsed.edges)
        ? parsed.edges
        : []
    return { graph: { nodes, links }, parseError: null }
  } catch {
    return {
      graph: null,
      parseError: 'Graph data is corrupt or incomplete. Re-run kepra-index on your vault.',
    }
  }
}

const { graph, parseError } = readGraphData()

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App graph={graph} parseError={parseError} />
  </StrictMode>,
)
